name: 'sales_pipeline'
version: '1.0.0'
config-version: 2

profile: 'sales_pipeline'

on-run-start:
  - "{{ log_dbt_run('dbt_run', 'started') }}"

on-run-end:
  - "{{ log_dbt_run('dbt_run', 'success') }}"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  sales_pipeline:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: table